before_script:
  - apt-get update -qq && apt-get install -y -qq python-pip
  - pip install -U platformio
  - platformio lib --global install ArduinoJson  
  - platformio lib --global install painlessMesh
  - platformio lib --global install https://github.com/latonita/PacketSerial

linux:
  script:
    - platformio ci --lib="." --board=esp12e esp-mesh-gateway/src/meshGate.cpp

